version: "3.8"
services:
  sse:
    image: 213.199.34.152:32768/innovclinic-sse:latest
    networks:
      - clinica
    ports:
      - 3300:3000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

networks:
  clinica:
    external: true